# Generated by Django 5.2.4 on 2025-07-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '프로젝트', 'verbose_name_plural': '프로젝트'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': '투표', 'verbose_name_plural': '투표'},
        ),
    ]
